---
title: "galaxy"
author: "Upal Chowdhury"
date: "December 12, 2016"
output: html_document
---

```{r,message=F}
library(caret)
library(corrplot)           
library(doParallel)
library(plyr)
library(doSNOW)
library(dplyr)
library(pROC) 
library(mlbench)
library(knitr)
library(randomForest)
```









```{r}

samsung_data <- read.csv("C:/Users/upalchow/Desktop/UT_Austin_dataanlytics/DataAnalyticsUnderstandingCustomers2016/course_3/galaxy_smallmatrix_labeled_8d.csv", stringsAsFactors = F)

dim(samsung_data)

samsung_data$galaxysentiment <- as.factor(samsung_data$galaxysentiment)


```


```{r}

nzv <- nearZeroVar(samsung_data, saveMetrics = TRUE)
dim(nzv[nzv$percentUnique > 0.1,]);




samsung_nzv   <-  as.data.frame(samsung_data[c(rownames(nzv[nzv$percentUnique >0.1,]))]);

str(samsung_nzv )



df <- cbind(as.data.frame(sapply(samsung_nzv,
    as.numeric)),samsungsentiment=samsung_data$galaxysentiment);

str(df)
head(samsung_data$galaxysentiment)



```

```{r}
df$samsungsentiment <- as.factor(df$samsungsentiment)

control.m <-
  trainControl(
  method = "repeatedcv",
  number = 10,
  repeats = 3,
  classProbs = F,
  savePredictions = T,
  allowParallel = TRUE
  )




cl <- makeCluster(8, type = "SOCK")
registerDoSNOW(cl)
modelrf_full <-
  train(
  df$samsungsentiment~.,
  data = df,
  method =  "rf",
  preProcess = c("center", "scale"),
  trControl = control.m
  )


```




```{r,eval=T}
varImp(modelrf_full)

str(df)
detach(df)

```


```{r}
detach(Ldf)
samsung_Large_matrix <- read.csv("C:/Users/upalchow/Desktop/UT_Austin_dataanlytics/DataAnalyticsUnderstandingCustomers2016/course_3/Newfolder/Concatenated2.csv", stringsAsFactors = F)

str(samsung_Large_matrix)
attach(samsung_Large_matrix)

newdf <-data.frame(iphonedisunc,iphonedisneg,iphoneperpos,iphonedispos,htcdispos,iphoneperneg,iphoneperunc,samsungperpos,samsungdispos,samsungdisneg,samsungperneg,samsungsentiment)

Ldf <- data.frame(samsung_Large_matrix[,colnames(newdf)])

Ldf[] <- lapply(Ldf,function(x) as.numeric(x))

Ldf$samsungsentiment <- as.factor(Ldf$samsungsentiment)






# str(df)
# 
# str(Ldf)
```


#prediction

```{r}
attach(Ldf)
predictions.f <- predict(modelrf_full,Ldf$samsungsentiment)
galaxysentiment <- predictions.f
str(predictions.f)



final_data <- data.frame(cbind(Ldf,galaxysentiment))
final_data <- final_data[,-12]
str(final_data$galaxysentiment)

kable(head(final_data,10))

write.csv(final_data,"C:/Users/upalchow/Desktop/UT_Austin_dataanlytics/DataAnalyticsUnderstandingCustomers2016/course_3/Newfolder/finaldata.csv")




```

